SELECT * FROM record;
SELECT * FROM specialize;
SELECT * FROM doctor;
SELECT * FROM publicservant;
SELECT * FROM users;
SELECT * FROM discover;
SELECT * FROM disease;
SELECT * FROM country;
SELECT * FROM diseasetype;